### ISSUE TITLE
account archive request

### ISSUE THREAD

**Issue by git-mf** [mattheworiordan/easybacklog#2]
hi,
i was, and still am, very thankful for you and the easybacklog project, that was a great tool.
i couldn't believe today that the main login page redirected me to github#end-of-life, i double-checked my inbox, spam and other folders looking up for some notification from the website but nothing.
could you please provide some way to get the data that was hosted on my account ?
thanks again.

**Comment by mattheworiordan** [comment]
Hi. I sent out emails to everyone at the end of Aug 2022 stating everything would shut down at the end of Sep. I let it run on for a bit longer. See below.

![MO screenshot 2023-02-07 at 14 31 54](https://user-images.githubusercontent.com/43789/217273704-844b5602-0ccb-499c-8554-98e0912f00b1.png)

I am afraid it's very difficult to give you access to your data now as a) it's archived away, b) it will require manual work to extract, c) it's a security risk as I can't share people's data.

If you can tell me which email address you used, and which backlog you need though, I will see if I can export the raw data into a CSV for you and send to the registered email address.  Would that work?

**Comment by groverharrison** [comment]
Hi Matthew,
 
Thank you for providing an amazing product!  I must have completely missed the email you sent out, and I'd also love to retrieve my data, if at all possible as I am hoping to keep using easybacklog as a stand-alone open source project. Is there a good, less public, line of communication I could send you the email and backlog name on?

Thank you again for creating such a simple yet immensely valuable tool!

**Comment by mattheworiordan** [comment]
> Is there a good, less public, line of communication

Sure, please send an email to this temp address fsrq4s7@shitmail.org

**Comment by mattheworiordan** [comment]
Closing as being resolved over email.

**Comment by git-mf** [comment]
> If you can tell me which email address you used, and which backlog you need though, I will see if I can export the raw data into a CSV for you and send to the registered email address. Would that work?

hi matthew,
as far as i can remember, i had 2 or 3 backlogs hosted on easy backlog.
could you please send them to git-mf@shitmail.org
thank you.

**Comment by mattheworiordan** [comment]
> as far as i can remember, i had 2 or 3 backlogs hosted on easy backlog.
> could you please send them to [git-mf@shitmail.org](mailto:git-mf@shitmail.org)

You haven't told me what email address you had your accounts with. Please send an email to [fsrq4s7@shitmail.org](mailto:fsrq4s7@shitmail.org) from the email address that matches your account, and I can send it back to that email address.

**Comment by git-mf** [comment]
> > as far as i can remember, i had 2 or 3 backlogs hosted on easy backlog.
> > could you please send them to [git-mf@shitmail.org](mailto:git-mf@shitmail.org)
> 
> You haven't told me what email address you had your accounts with. Please send an email to [fsrq4s7@shitmail.org](mailto:fsrq4s7@shitmail.org) from the email address that matches your account, and I can send it back to that email address.

email sent from m..i@..il.com
thank you
